/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Janelas;

import Classes.Funcionario;
import java.sql.Date;

/**
 *
 * @author 20152134110070
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    String cpf;
    String nome;
    String sexo;
    Date data_nasc;
    Date data_admissao;
    String endereco;
    float salario;
    String telefone;
    String horario;
    String login;
    String senha;
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 126, 14);

        jTextField1.setText("118.721.504-03");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(40, 40, 88, 29);

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 102, 72, 14);

        jTextField2.setText("Edilson Fernandes");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(40, 122, 238, 30);

        jLabel3.setText("Dt. Admissão:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(357, 18, 90, 27);

        jTextField3.setText("1994-10-20");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(357, 38, 90, 31);

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(315, 156, 90, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Feminino");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(315, 193, 90, 15);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Masculino");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(315, 172, 90, 18);

        jLabel5.setText("Dt. Nascimento:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 156, 101, 14);

        jTextField4.setText("1994-10-20");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(40, 176, 88, 29);

        jLabel6.setText("Idade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(178, 156, 75, 14);

        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(178, 176, 60, 29);

        jLabel7.setText("Endereço:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 230, 88, 14);

        jTextField6.setText("hfdkjfhdkfhk");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(40, 250, 368, 29);

        jLabel12.setText("Contato:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(240, 310, 113, 14);

        jTextField11.setText("(xx) xxxxx-xxxx");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(250, 330, 96, 30);

        jLabel14.setText("E-mail:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 310, 96, 14);

        jTextField13.setText("edilsonfernandes312@gmail.com");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(40, 330, 190, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 41));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add-1-icon.png"))); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 450, 110, 29);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 220, 407, 10);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField14.setText("edilson233");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Login:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Senha:");

        jTextField15.setText("123");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 380, 351, 100);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(40, 290, 405, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(40, 80, 407, 10);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-30083 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(465, 80, 223, 256);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Manhã");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(430, 410, 120, 23);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Tarde");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(430, 430, 120, 23);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Noite");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(430, 450, 120, 23);

        jLabel8.setText("Turno:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 390, 80, 14);

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh_arrow_1546.png"))); // NOI18N
        jButton5.setText("Atualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 410, 110, 30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Funcionario f = new Funcionario();
        cpf = jTextField1.getText();
        nome = jTextField2.getText();
        if (jRadioButton1.isSelected()){
            sexo = "F";
        } else {
            sexo = "M";
        }
        data_nasc = Date.valueOf(jTextField4.getText());
        data_admissao = Date.valueOf(jTextField3.getText());
        endereco = jTextField6.getText();
        salario = 500f;
        telefone = jTextField11.getText();
        if (jRadioButton3.isSelected()){
            horario = "Manhã";
        } else if (jRadioButton4.isSelected()){
            horario = "Tarde";
        } else if (jRadioButton5.isSelected()){
            horario = "Noite";
        }
        login = jTextField14.getText();
        senha = jTextField15.getText();
        
        f.abrirConexao();
        f.cadastrarFc(cpf, nome, sexo, data_nasc,data_admissao, endereco, salario, telefone, horario, login, senha);
        f.fecharConexao();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = new Funcionario();
        funcionario.abrirConexao();
        cpf = jTextField1.getText();
        nome = jTextField2.getText();
        if (jRadioButton1.isSelected()){
            sexo = "M";
        } else {
            sexo = "F";
        }
        if (jRadioButton3.isSelected()){
            horario = "Manhã";
        } else if (jRadioButton4.isSelected()){
            horario = "Tarde";
        } else if (jRadioButton5.isSelected()){
            horario = "Noite";
        }
        data_nasc = Date.valueOf(jTextField4.getText());
        data_admissao = Date.valueOf(jTextField3.getText());
        endereco = jTextField6.getText();
        telefone = jTextField11.getText();
        funcionario.atualizarFc(cpf, nome, sexo, data_nasc, data_admissao, endereco, salario, telefone, horario, login, senha);
        funcionario.fecharConexao();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JRadioButton jRadioButton4;
    public static javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField11;
    public static javax.swing.JTextField jTextField13;
    public static javax.swing.JTextField jTextField14;
    public static javax.swing.JTextField jTextField15;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
